services:
  postgres:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: itk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: