spring.application.name=itk

spring.datasource.url=jdbc:postgresql://postgres:5432/itk
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener=INFO
